### ISSUE TITLE
Do we also need rename package to org.spark_packages or something?

### ISSUE THREAD

**Issue by lw-lin** [spark-packages/dstream-akka#3]
hi @zsxwing 

I tried to build `dstream-akka`, `dstream-twitter` after you moved them here and uploaded the build scripts, and the builds  all turned out successful. So thank you for the great jobs you've done!

I'm issuing this ticket because I wonder, do we also need rename package from `org.apache.spark.streaming` to `org.spark_packages.streaming` or something? If so, do you mind if I help do the renaming for the 5 packages (which I would love to help with)? Thanks!

**Comment by rxin** [comment]
If we rename it, we break compatibility for all existing streaming apps that use these sources.
